name: Header Generator Tests

on:
  release:
    types: [created]
  push:
    branches: '*'
    paths:
    - "header-gen/**"
    - "**/header-gen.yml"
  pull_request:
    branches: '*'
    paths:
    - "header-gen/**"
    - "**/header-gen.yml"

jobs:
  build-and-test:
    name: Build & Test TS lib
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        registry-url: "https://npm.pkg.github.com"
        cache: npm
        cache-dependency-path: header-gen/package-lock.json

    - name: Install Dependencies
      run: npm ci
      working-directory: ./header-gen

    - name: Update version
      uses: microbit-foundation/npm-package-versioner-action@v1
      with:
        working-directory: ./header-gen

    - name: Build
      run: npm run build
      working-directory: ./header-gen

    - name: Run Jest Tests
      run: npm test
      working-directory: ./header-gen

    - name: Publish
      run: npm publish
      if: github.ref == 'refs/heads/main' || github.event_name == 'release' && github.event.action == 'created'
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
