name: Header Generator Tests

on:
  push:
    branches: '*'
  pull_request:
    branches: '*'

jobs:
  build-and-test:
    name: Build & Test TS lib
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      run: npm ci
      working-directory: ./header-gen

    - name: Build
      run: npm run build
      working-directory: ./header-gen

    - name: Run Jest Tests
      run: npm test
      working-directory: ./header-gen
